### ISSUE TITLE
Rewrite #RenegadePython Tweets for Accessibility

### ISSUE THREAD

**Issue by jrg94** [TheRenegadeCoder/how-to-python-code#11]
Check out [this tweet](https://twitter.com/RenegadeCoder94/status/1278776602206273538) for context, but to summarize:

I've been using Carbon for challenges because the images are pretty and Twitter doesn't handle syntax highlighting, etc. I had been adding ALT tags but just to describe the image, not to include the actual code snippet. Now that we're storing the source code here, I'm going to start linking that instead. Also, I think I'm going redo all of the tweets, so they're properly accessible (since they get linked in my articles).

**Comment by Muhimen123** [comment]
That might cause some pain(updating all the posts). But you can still keep the carbon screenshots.

**Comment by jrg94** [comment]
I think what I'm going to do is embed the carbon screenshots in the READMEs alongside the challenge descriptions.
