### ISSUE TITLE
How to Increment a Number Challenge Is Unclear

### ISSUE THREAD

**Issue by Muhimen123** [TheRenegadeCoder/how-to-python-code#18]
I was trying to solve [this challenge](https://therenegadecoder.com/code/how-to-increment-a-number-in-python/#challenge). But I got stuck at one point. The question, will I take only one number as input and perform a single operation? Or keep going through the process until we reach a dead-end(specified).

**Comment by jrg94** [comment]
Yeah, your initial intuition is right. This increment function would work just like an increment operator. It would take one input and change based on its current status. I'll include an example in the article that looks some like the following:

```python
inc(7)  # returns 8
inc(4)  # returns 7
inc(5)  # returns 11
```
