### ISSUE TITLE
Bug Report: the input of Formatting a String

### ISSUE THREAD

**Issue by JiaxiangBU** [TheRenegadeCoder/how-to-python-code#2]
The input 
```python
name = Jeremy
```

should be 

```python
name = 'Jeremy'
```

Here is the article url https://therenegadecoder.com/code/python-code-snippets-for-everyday-problems/

**Comment by jrg94** [comment]
Nice catch! This is actually an issue in the source article as well and pretty much anywhere this was syndicated. I'll fix this up now.

**Comment by jrg94** [comment]
Alright! That should be all patched up. Let me know if you see any other issues like that.
