### ISSUE TITLE
Design Hierarchical Challenges

### ISSUE THREAD

**Issue by jrg94** [TheRenegadeCoder/how-to-python-code#23]
When I was building up [my list of code snippets](https://therenegadecoder.com/code/python-code-snippets-for-everyday-problems/), I started organizing them by category. I'm wondering if we should update the challenges section of this repo to match this hierarchy.

**Comment by Muhimen123** [comment]
Currently, we don't have much of the challenge solution so things might look quite empty. But I think it will be pretty beneficial in the long run. We should definitely do that.

**Comment by jrg94** [comment]
I'm going to close this out for now. This would be a breaking change for the README table.
