### ISSUE TITLE
Create How to Swap Variables Jupyter Notebook

### ISSUE THREAD

**Issue by jrg94** [TheRenegadeCoder/how-to-python-code#29]
Add solutions from this article to a Jupyter notebook: https://therenegadecoder.com/code/how-to-swap-variables-in-python/

See here for an example: https://colab.research.google.com/github/TheRenegadeCoder/how-to-python-code/blob/master/notebooks/how_to_write_a_loop.ipynb

**Comment by Atharva0045** [comment]
I would like to work on the listed issue
