### ISSUE TITLE
Create Jupyter Notebook for "How to Loop Over a Dictionary"

### ISSUE THREAD

**Issue by jrg94** [TheRenegadeCoder/how-to-python-code#5]
Here's the original article: https://therenegadecoder.com/code/how-to-loop-over-a-dictionary-in-python/

Basically, I need the code snippets from that article loaded into a Jupyter notebook. For simplicity, I've been using Google Colab, but any platform which hosts notebooks would be fine (and preferred). 

Here's a sample notebook to give you an idea of what I'm talking about: https://colab.research.google.com/github/TheRenegadeCoder/how-to-python-code/blob/master/notebooks/how_to_write_a_list_comprehension.ipynb

**Comment by jrg94** [comment]
I closed this, but we'll need to link the new notebook in the README. Right now, there isn't a button to link to Google Colab (or some other service). Though, I think we can construct the link manually. The button isn't necessary.

**Comment by Muhimen123** [comment]
I wrote the notebook in Jupyter lab. How can I link it to Google Colab?

**Comment by jrg94** [comment]
I believe Google Colab just needs a link to the GitHub file. Here's the link that worked for me: https://colab.research.google.com/github/TheRenegadeCoder/how-to-python-code/blob/master/notebooks/how_to_loop_over_a_dictionary.ipynb
