### ISSUE TITLE
Add Challenge Link for "How to Create a List"

### ISSUE THREAD

**Issue by jrg94** [TheRenegadeCoder/how-to-python-code#6]
Here's the source article: https://therenegadecoder.com/code/how-to-create-a-list-in-python/

Here's a quick summary of the challenge: 

> create a list which contains the first 100 terms of the fibonacci sequence

For this, I'd be content with the solution being written and added to the challenges folder as Python source code. If you want to go the extra mile, you can use [Carbon](https://carbon.now.sh/) to create an image of the code snippet to post on Twitter with the hashtag [#RenegadePython[(https://twitter.com/hashtag/RenegadePython). If you do that, you can link the tweet in the README, and I'll share your tweet in the article.

**Comment by Muhimen123** [comment]
I am not sure about what to do on this one 😅

**Comment by jrg94** [comment]
No problem! I'll try to explain it a bit better.

First, I've started storing challenge scripts here: https://github.com/TheRenegadeCoder/how-to-python-code/tree/master/challenges

The challenges come from the articles in the README table. For instance, [How to Round a Number](https://therenegadecoder.com/code/how-to-round-a-number-in-python/#challenge) has a rounding challenge at the end of the article.

These challenges are relatively new, so not all articles have them. That said, the articles that do have them don't always have a solution—which would be embedded directly in the article [as a Tweet](https://twitter.com/RenegadeCoder94/status/1270232431325478915). 

I've been trying to go back through all the articles to both add challenges and come up with solutions. For example, this issue is related to the "How to Create a List" article which has a challenge that you can find here: https://therenegadecoder.com/code/how-to-create-a-list-in-python/#challenge

If you want to help with this, you can create a solution to this challenge and place it in the challenges folder. Alternatively, you can create a Tweet with the solution and link that tweet in the README. Either way is fine!

**Comment by Muhimen123** [comment]
I don't have a Twitter account. So, I will go with the first one. 😊

**Comment by jrg94** [comment]
Sounds good! If you want, I'd be happy to post the solution on your behalf.

**Comment by jrg94** [comment]
Alright, this has officially been updated! Do you want me to create more issues for you? Or are you comfortable with creating some based off holes in the README?

**Comment by Muhimen123** [comment]
Sorry for late reply, I was shifting my house. More issues will surely be helpful. However, I will try to find holes in the README.

**Comment by jrg94** [comment]
No problem! I actually just moved as well, so that works out.
